### PR TITLE
add authentication

### LINKED ISSUE #14: Lodestar-Prater authtication needed
tracked by https://github.com/dappnode/DAppNodePackage-web3signer-prater/issues/71

Add authentication for validator and web3signer communication

### PR DESCRIPTION
**Pull request by alexpeterson91**
Gonna need help with this one @dapplion I looked everywhere i could and found this in a 6 month old thread on GH you wrote and am just kinda winging the execution, please assist and we can get your client added and have all the ELs and CLs on Dappnode Finally

### CODE REVIEW

**Comment by alexpeterson91** [comment]
will close #14

**Comment by dapplion** [comment]
Yes sorry we are missing docs for this use-case.

To authenticate the web3signer calls to the Lodestar validator client, it expects file with name `api-token.txt` https://github.com/ChainSafe/lodestar/blob/30a88a2efcfff09145c7d0cb77bb877ad2b0317b/packages/cli/src/cmds/validator/keymanager/server.ts#L31in the dbPath directory https://github.com/ChainSafe/lodestar/blob/30a88a2efcfff09145c7d0cb77bb877ad2b0317b/packages/cli/src/cmds/validator/handler.ts#L153 so

```
$dataDir/validator-db/api-token.txt
```

**Comment by dapplion** [comment]
You must add a new docker volume for the validator like in other clients, below here
https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/blob/c119b7bd579795375da938da390a815635dc0efb/docker-compose.yml#L42

Then map it to some path that makes sense like
```yaml
    volumes:
      - "validator-data:/var/lib/data"
```
Then in the validator command set `--dataDir /var/lib/data` and copy the token file to `/var/lib/data/validator-db/api-token.txt`

**Comment by alexpeterson91** [comment]
@dapplion can you take another look?

**Review by dapplion — APPROVED** [review]
LGTM, can you test if web3signer comms work good?

**Comment by alexpeterson91** [comment]
> LGTM, can you test if web3signer comms work good?

of course

**Pull request merged**
